# 镜像仓库: https://hub.docker.com/
version: '3'
services:

  # Nginx 服务
  nginx:
    image: 'nginx:1.25'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf # 配置目录
      - '~/data/nginx/logs:/var/log/nginx' # 日志目录
      - '~/data/nginx/html:/usr/share/nginx/html' # 网站目录
      - '~/data/nginx/cert:/etc/nginx/cert' # 证书目录
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      TZ: Asia/Shanghai
    networks:
      - custom-local-network

# 自定义内部网络
networks:
  custom-local-network:
    driver: bridge # 桥接模式